---
- name: "New provision script to setup ec2 Instance"
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  vars:
    keyname: backontrackaws
    region: ap-south-1
    image: ami-068257025f72f470d
    sec_group: ansible-lab
    instance_type: t2.micro
    count: 1
    debug_enable: true
  tasks:
    - name: "Create a new key pair"
      ec2_key:
        name: "{{ keyname }}"
        region: "{{ region }}"
        ec2_access_key: "{{ ec2_access_key }}"
        ec2_secret_key: "{{ ec2_secret_key }}"
      register: ec2_keyout
    - debug:
        var: ec2_keyout
    - name: "Saving Key for access"
      copy:
        content: "{{ ec2_keyout.key.private_key }}"
        dest: "{{ keyname }}.pem"
        mode: "0400"
      when: ec2_keyout.changed
    - name: Create security group
      ec2_group:
        name: "{{ sec_group }}"
        description: "Sec group for app"
        region: "{{ region }}"
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on ssh port
      register: result_sec_group
    - debug:
        var: result_sec_group
        
    - name: "Creating a new Ec2 Instance"
      ec2:
        ec2_access_key: "{{ ec2_access_key }}"
        ec2_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        group: "{{ sec_group }}"
        keypair: "{{ keyname }}"
        count: 1
        wait: true
        wait_timeout: 500
        count_tag:
          name: "Ansible/Jain"
          instance_tags:
          Name: "Ansible/Master"
      register: master_output
    - debug:
        var: master_output
    - debug:
        var: master_output.instances.0.public_ip

    - name: "Waiting for master to come online"
      wait_for:
        port: 22
        host: "{{ master_output.instances.0.public_ip }}"
        timeout: 20
        state: started
        delay: 5
